# Generated by Django 5.0.1 on 2024-02-15 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0002_applicantprofile_brazo_derecho_and_more'),
        ('job_offers', '0005_alter_joboffer_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Enviado', 'Enviado'), ('En Revisión', 'En Revisión'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], default='Enviado', max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicants.applicantprofile')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_offers.joboffer')),
            ],
        ),
    ]
