# Generated by Django 5.0.1 on 2024-02-26 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0011_alter_applicantprofile_state'),
        ('job_applications', '0002_jobapplication_fecha_fin_jobapplication_fecha_inicio_and_more'),
        ('job_offers', '0010_alter_joboffer_max_salary_alter_joboffer_min_salary'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('candidate', 'job_offer')},
        ),
    ]
