# Generated by Django 5.0.1 on 2024-02-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='company_description',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='phone',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
