# Generated by Django 5.0.1 on 2024-02-21 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_employerprofile_company_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='phone',
        ),
    ]
