# Generated by Django 5.0.1 on 2024-02-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_remove_employerprofile_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='industry',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='exterior_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='interior_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='municipality',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='neighborhood',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='postal_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='street_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
