# Generated by Django 5.0.1 on 2024-02-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='brazo_derecho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='brazo_izquierdo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='cuello',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='espalda',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='exterior_number',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='interior_number',
            field=models.CharField(blank=True, default='None', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='mano_derecha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='mano_izquierda',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='municipality',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='neighborhood',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='no_especificado',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='oido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='pie_derecho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='pie_izquierdo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='pierna_derecha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='pierna_izquierda',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='postal_code',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='sistema_cardiovascular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='sistema_neurologico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='sistema_neurologico_sistema_nervioso_periferico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='sistema_respiratorio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='state',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='street_address',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='tacto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='vista',
            field=models.BooleanField(default=False),
        ),
    ]
