# Generated by Django 5.0.1 on 2024-02-12 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0002_joboffer_brazo_derecho_joboffer_brazo_izquierdo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='exterior_number',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='interior_number',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='street_address',
        ),
    ]
