# Generated by Django 5.0.1 on 2024-02-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0005_alter_joboffer_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='salary',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='max_salary',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='min_salary',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
