# Generated by Django 5.0.1 on 2024-02-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0006_remove_joboffer_salary_joboffer_max_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='municipality',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='job_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='job_type',
            field=models.CharField(choices=[('Tiempo Completo', 'Tiempo Completo'), ('Medio Tiempo', 'Medio Tiempo'), ('Becario', 'Becario'), ('Temporal', 'Temporal'), ('Contrato', 'Contrato')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='max_salary',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='min_salary',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
