# Generated by Django 5.0.1 on 2024-02-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0009_alter_joboffer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='max_salary',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='min_salary',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
