# Generated by Django 5.0.2 on 2024-03-04 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0011_remove_joboffer_brazo_derecho_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='adaptaciones_fisicaMotora',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='adaptaciones_intelectual',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='adaptaciones_psiquica',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='adaptaciones_sensorial',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='afectacion_fisicaMotora',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='afectacion_sensorial',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='descripcion_fisicaMotora',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='descripcion_intelectual',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='descripcion_psiquica',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='descripcion_sensorial',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='independencia',
        ),
    ]
