# Generated by Django 5.0.1 on 2024-02-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_applicantprofile_brazo_derecho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='industry',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='last_names',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='phone',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='school',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='title',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
