# Generated by Django 5.0.1 on 2024-02-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_applicantprofile_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='city',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
