# Generated by Django 5.0.1 on 2024-02-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0004_applicantprofile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
    ]
