# Generated by Django 5.0.1 on 2024-02-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0006_alter_applicantprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='exterior_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='industry',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='interior_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='municipality',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='neighborhood',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='postal_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='school',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='street_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
