# Generated by Django 5.0.1 on 2024-02-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0007_alter_applicantprofile_exterior_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='municipality',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
