# Generated by Django 5.0.1 on 2024-02-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0008_alter_applicantprofile_municipality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='exterior_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='industry',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='interior_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='neighborhood',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='postal_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='school',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='street_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
