# Generated by Django 5.0.1 on 2024-03-04 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0011_alter_applicantprofile_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantprofile',
            old_name='school',
            new_name='education',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='brazo_derecho',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='brazo_izquierdo',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='cuello',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='espalda',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='exterior_number',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='interior_number',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='mano_derecha',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='mano_izquierda',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='no_especificado',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='oido',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='pie_derecho',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='pie_izquierdo',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='pierna_derecha',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='pierna_izquierda',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='sistema_cardiovascular',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='sistema_neurologico',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='sistema_neurologico_sistema_nervioso_periferico',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='sistema_respiratorio',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='tacto',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='vista',
        ),
    ]
