# Generated by Django 5.0.1 on 2024-03-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0012_rename_school_applicantprofile_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionParteFisicaMotora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(choices=[('Brazos', 'Brazos'), ('Manos ', 'Manos '), ('Dedos', 'Dedos'), ('Piernas', 'Piernas'), ('Pies', 'Pies'), ('Columna Vertebral', 'Columna Vertebral'), ('Tronco', 'Tronco')])),
            ],
        ),
        migrations.CreateModel(
            name='OpcionParteIntelectual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(choices=[('Memoria', 'Memoria'), ('Razonamiento Lógico', 'Razonamiento Lógico'), ('Habilidades Sociales', 'Habilidades Sociales'), ('Habilidades Motoras', 'Habilidades Motoras'), ('Aprendizaje Académico', 'Aprendizaje Académico')])),
            ],
        ),
        migrations.CreateModel(
            name='OpcionPartePsiquica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(choices=[('Trastornos del Estado de Ánimo', 'Trastornos del Estado de Ánimo'), ('Trastornos de Ansiedad', 'Trastornos de Ansiedad'), ('Trastornos de la Personalidad', 'Trastornos de la Personalidad')])),
            ],
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='adaptaciones_fisicaMotora',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='adaptaciones_intelectual',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='adaptaciones_psiquica',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='adaptaciones_sensorial',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='afectacion_fisicaMotora',
            field=models.CharField(blank=True, choices=[('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave')], max_length=250),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='afectacion_sensorial',
            field=models.CharField(blank=True, choices=[('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave')], max_length=250),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='descripcion_fisicaMotora',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='descripcion_intelectual',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='descripcion_psiquica',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='descripcion_sensorial',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='independencia',
            field=models.CharField(blank=True, choices=[('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave')], max_length=250),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='opcion_sensorial',
            field=models.CharField(blank=True, choices=[('Visual', 'Visual'), ('Manos ', 'Manos '), ('Dedos', 'Dedos')]),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='opcion_fisicaMotora',
            field=models.ManyToManyField(blank=True, choices=[('Brazos', 'Brazos'), ('Manos ', 'Manos '), ('Dedos', 'Dedos'), ('Piernas', 'Piernas'), ('Pies', 'Pies'), ('Columna Vertebral', 'Columna Vertebral'), ('Tronco', 'Tronco')], to='applicants.opcionpartefisicamotora'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='opcion_intelectual',
            field=models.ManyToManyField(blank=True, choices=[('Memoria', 'Memoria'), ('Razonamiento Lógico', 'Razonamiento Lógico'), ('Habilidades Sociales', 'Habilidades Sociales'), ('Habilidades Motoras', 'Habilidades Motoras'), ('Aprendizaje Académico', 'Aprendizaje Académico')], to='applicants.opcionparteintelectual'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='opcion_psiquica',
            field=models.ManyToManyField(blank=True, choices=[('Trastornos del Estado de Ánimo', 'Trastornos del Estado de Ánimo'), ('Trastornos de Ansiedad', 'Trastornos de Ansiedad'), ('Trastornos de la Personalidad', 'Trastornos de la Personalidad')], to='applicants.opcionpartepsiquica'),
        ),
    ]
