# Generated by Django 5.0.1 on 2024-03-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0013_opcionpartefisicamotora_opcionparteintelectual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcionpartefisicamotora',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='opcionparteintelectual',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='opcionpartepsiquica',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
