# Generated by Django 5.0.2 on 2024-03-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0015_alter_opcionpartefisicamotora_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='opcion_intelectual',
            field=models.ManyToManyField(blank=True, to='applicants.opcionparteintelectual'),
        ),
    ]
