# Generated by Django 5.0.2 on 2024-03-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0016_alter_applicantprofile_opcion_intelectual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='opcion_fisicaMotora',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='opcion_intelectual',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='opcion_psiquica',
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='afectacion_fisicaMotora',
            field=models.CharField(blank=True, choices=[('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave')]),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='afectacion_sensorial',
            field=models.CharField(blank=True, choices=[('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave')]),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='independencia',
            field=models.CharField(blank=True, choices=[('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave')]),
        ),
        migrations.DeleteModel(
            name='OpcionParteFisicaMotora',
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='opcion_fisicaMotora',
            field=models.CharField(blank=True, choices=[('Brazos', 'Brazos'), ('Manos ', 'Manos '), ('Dedos', 'Dedos'), ('Piernas', 'Piernas'), ('Pies', 'Pies'), ('Columna Vertebral', 'Columna Vertebral'), ('Tronco', 'Tronco')]),
        ),
        migrations.DeleteModel(
            name='OpcionParteIntelectual',
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='opcion_intelectual',
            field=models.CharField(blank=True, choices=[('Memoria', 'Memoria'), ('Razonamiento Lógico', 'Razonamiento Lógico'), ('Habilidades Sociales', 'Habilidades Sociales'), ('Habilidades Motoras', 'Habilidades Motoras'), ('Aprendizaje Académico', 'Aprendizaje Académico')]),
        ),
        migrations.DeleteModel(
            name='OpcionPartePsiquica',
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='opcion_psiquica',
            field=models.CharField(blank=True, choices=[('Trastornos del Estado de Ánimo', 'Trastornos del Estado de Ánimo'), ('Trastornos de Ansiedad', 'Trastornos de Ansiedad'), ('Trastornos de la Personalidad', 'Trastornos de la Personalidad')]),
        ),
    ]
